version: '2.4'

networks:
  car_service:
    external: true

services:
  car_service_front_app:
    container_name: car_service_front_app
    image: car-service-front-dev
    volumes:
      - .:/var/www/car-service-front/current
      - ~/.ssh/:/home/www-data/.ssh/
      - .docker/app/conf/my.ini:/usr/local/etc/php/php.ini
    environment:
      APPLICATION_ENV: dev
    networks:
      - car_service
    domainname: car-service-front.local
    hostname: app.car-service-front

  car_service_front_nginx:
    container_name: car_service_front_nginx
    image: car-service-front-nginx
    ports:
      - ${NGINX_PORT}:8601
    volumes:
      - .:/var/www/car-service-front/current
      - .docker/nginx/conf/nginx.conf:/etc/nginx/nginx.conf
      - .docker/nginx/conf.d/car-service.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - car_service_front_app
    networks:
      - car_service
    domainname: car-service-front.local
    hostname: nginx.car-service-front
