# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true      # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: '../src/*'
        exclude: '../src/{DependencyInjection,Entity,Migrations,Tests,Kernel.php}'

    # controllers are imported separately to make sure services can be injected
    # as action arguments even if you don't extend any base controller class
    App\Controller\:
        resource: '../src/Controller'
        tags: ['controller.service_arguments']

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones

    App\EventSubscriber\KnpMenuBuilderSubscriber:
        arguments:
            $menuItems: '%side_menu%'

    app.service.position_service:
        class: App\Service\PositionService
        arguments:
            $client: '@app.clients.car_service.client'

    App\Form\EmployeeForm:
        arguments:
            $positionService: '@app.service.position_service'

    App\Form\WorkForm:
        arguments:
            $positionService: '@app.service.position_service'

    app.service.employee_service:
        class: App\Service\EmployeeService
        arguments:
            $client: '@app.clients.car_service.client'
            $extractor: '@app.extractor.employee_extractor'
            $hydrator: '@app.hydrator.employee_show_hydrator'

    App\Controller\EmployeeController:
        arguments:
            $employeeService: '@app.service.employee_service'

    App\Controller\WorkController:
        arguments:
            $workService: '@app.service.work_service'

    App\Controller\CustomerController:
        arguments:
            $customerService: '@app.service.customer_service'

    App\Controller\OrderController:
        arguments:
            $orderService: '@app.service.order_service'

    App\Controller\CarController:
        arguments:
            $carService: '@app.service.car_service'

    App\Controller\HomeController:
        arguments:
            $resumeService: '@app.service.resume_service'

    app.service.work_service:
        class: App\Service\WorkService
        arguments:
            $client: '@app.clients.car_service.client'
            $extractor: '@app.extractor.work_extractor'

    app.service.order_service:
        class: App\Service\OrderService
        arguments:
            $client: '@app.clients.car_service.client'
            $hydrator: '@app.hydrator.order_hydrator'

    app.service.customer_service:
        class: App\Service\CustomerService
        arguments:
            $client: '@app.clients.car_service.client'
            $extractor: '@app.extractor.customer_extractor'
            $hydrator: '@app.hydrator.customer_hydrator'

    app.service.car_service:
        class: App\Service\CarService
        arguments:
            $client: '@app.clients.car_service.client'
            $extractor: '@app.extractor.car_extractor'
            $hydrator: '@app.hydrator.car_show_hydrator'

    app.service.resume_service:
        class: App\Service\ResumeService
        arguments:
            $client: '@app.clients.car_service.client'
            $hydrator: '@app.hydrator.resume_hydrator'

imports:
    - { resource: services/clients.yaml }
    - { resource: services/extractors.yaml }
    - { resource: services/serializers.yaml }
    - { resource: services/data-tables.yaml }
    - { resource: services/hydrators.yaml }
